dist: trusty
language: node_js

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./server/node_modules
    - ./client/node_modules

jobs:
  include:
    - before_script:
        - docker build -f docker/server/test.Dockerfile -t strangesast/core_server_dev .
      script:
      - docker run strangesast/core_server_dev npm test
    - before_script:
        - docker build -f docker/client/test.Dockerfile -t strangesast/core_client_dev .
      script:
      - docker run strangesast/core_client_dev ng lint
      - docker run strangesast/core_client_dev ng test
      - docker run strangesast/core_client_dev ng e2e
      - docker run strangesast/core_client_dev ng build --prod --base-href https://strangesast.github.io/core/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: client/dist/core
  on:
    branch: beta
