dist: trusty
language: node_js
node_js:
  - 12

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm i -g npm
  - npm i -g @angular/cli

cache:
  directories:
    - ./server/node_modules
    - ./client/node_modules

jobs:
  include:
    - before_script:
        - docker build -f docker/server/test.Dockerfile -t strangesast/core_server_dev .
      script:
      - docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" strangesast/core_server_dev npm test
    - before_script:
      - cd ./client/
      - npm install
      script:
      - npm run-script lint
      - npm run-script test:ci
      - npm run-script e2e
      - npm run-script build:ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: client/dist/core
  on:
    branch: beta
