version: '3.7'
services:
#  mongo:
#    image: 'mongo'
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_CREATE_TOPICS: "input:1:1"
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  monitoring:
#    build:
#      context: .
#      dockerfile: docker/monitoring/Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      KAFKA_HOST: kafka
#      BASE_URL: "http://10.0.0.101:5000"
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "8080:80"
#  server:
#    build:
#      context: .
#      dockerfile: docker/server/Dockerfile
